// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Academiccalendar struct {
	ID           int32
	SemesterID   int32
	Daynumber    int32
	SubjectID    pgtype.Int4
	CurriculumID pgtype.Int4
	ExamID       pgtype.Int4
	HolidayID    pgtype.Int4
	Description  pgtype.Text
}

type Academicyear struct {
	ID        int32
	Startdate pgtype.Date
}

type Categoriestyp struct {
	ID   int32
	Name string
}

type Category struct {
	ID     int32
	TypeID int32
	Name   string
}

type Curriculum struct {
	ID          int32
	SubjectID   int32
	Description string
}

type Curriculumschedule struct {
	ID           int32
	CurriculumID int32
	SubjectID    int32
	SemesterID   int32
	Dayoffset    int32
	Description  string
}

type Exam struct {
	ID          int32
	SubjectID   int32
	CategoryID  int32
	Description string
	Date        pgtype.Date
}

type Holiday struct {
	ID         int32
	CategoryID int32
	Date       pgtype.Date
}

type Semester struct {
	ID            int32
	YearID        int32
	Name          string
	Startdate     pgtype.Date
	Weeksduration int32
}

type Subject struct {
	ID   int32
	Name string
}
