// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Academiccalendar struct {
	Calendarid   int32
	Semesterid   int32
	Daynumber    int32
	Subjectid    pgtype.Int4
	Curriculumid pgtype.Int4
	Examid       pgtype.Int4
	Holidayid    pgtype.Int4
	Description  pgtype.Text
}

type Academicyear struct {
	Yearid    int32
	Startdate pgtype.Date
	Enddate   pgtype.Date
}

type Category struct {
	Categoryid int32
	Name       string
}

type Curriculum struct {
	Curriculumid int32
	Subjectid    int32
	Description  string
}

type Curriculumschedule struct {
	Scheduleid   int32
	Curriculumid int32
	Subjectid    int32
	Semesterid   int32
	Dayoffset    int32
	Description  string
}

type Exam struct {
	Examid      int32
	Subjectid   int32
	Categoryid  int32
	Description string
	Date        string
}

type Holiday struct {
	Holidayid  int32
	Categoryid int32
	Date       string
}

type Semester struct {
	Semesterid    int32
	Yearid        int32
	Name          string
	Startdate     pgtype.Date
	Weeksduration int32
}

type Subject struct {
	Subjectid int32
	Name      string
}
